#developer settings
VERSION = "1.3"
WINDOW_SIZE = (800, 600)
WINDOW_TITLE = "Tic-Tac-Toe"
GAME_FONT = "Comic Sans MS"
INPUT_FIELD_SIZE = (500, 75)
INPUT_FIELD_BORDER_WIDTH = 3
INPUT_TEXT_INDENT_LEFT = 5
MSG_DISTANCE_FROM_INPUT_FIELD = 50
MIN_NAME_LENGTH = 3
PROMPT_MSG_FONT_SIZE = 90
STATUS_FONT_SIZE = 60
SCORE_FONT_SIZE = 70
INPUT_FONT_SIZE = 90
CELL_SIZE = 100
FIELD_LINE_WIDTH = 5
WIN_LINE_WIDTH = 10
FIELD_Y = 30
STATUS_WIDGET_DISTANCE_FROM_FIELD = 25
SCORE_WIDGET_DISTANCE_FROM_BOTTOM = 175
SCORE_DISTANCE_FROM_WORD_SCORE = 45
GAME_ROUND_DELAY = 1000
SCREAMER_DURATION = 20

# colors
WHITE = (240,240,240)
BLACK = (0,0,0)
RED = (240,0,0)

# game constants
VOID = 0
ZERO = 1
CROSS = 2

